#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t cm"

$L "  _      _                              ____   _____ "
$L " | |    (_)                            / __ \ / ____|";
$L " | |     _ _ __   ___  __ _  __ _  ___| |  | | (___  ";
$L " | |    | | '_ \ / _ \/ _` |/ _` |/ _ \ |  | |\___ \ ";
$L " | |____| | | | |  __/ (_| | (_| |  __/ |__| |____) |";
$L " |______|_|_| |_|\___|\__,_|\__, |\___|\____/|_____/ ";
$L "                             __/ |                   ";
$L "                            |___/                    ";
$L "Welcome to Android `getprop ro.build.version.release` / LineageOS-`getprop ro.cm.version`";
